# Generated by generate_sensors.py
import esphome.codegen as cg
import esphome.config_validation as cv

from esphome.const import (
    CONF_ID
)

CONF_COMP_ID = "espaltherma_id"
espaltherma_ns = cg.esphome_ns.namespace('espaltherma')
ESPAlthermaComponent = espaltherma_ns.class_('ESPAlthermaComponent', cg.PollingComponent)

CONFIG_SCHEMA = (
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(ESPAlthermaComponent),
        }
    ).extend(cv.COMPONENT_SCHEMA)
)

var = None

async def to_code(config):
  print("__init__.to_code")
  var = cg.new_Pvariable(config[CONF_ID])
  await cg.register_component(var, config)
  print("===> " + str(var))
