import os
import re
from typing import Set, List

class SensorMetaData:
    def __init__(self, description, unit_type, unique_id):
        self.unique_id = unique_id
        self.description = description
        self.unit_type = unit_type

        if (unit_type == "bool"):
          self.sensor_type = "binary_sensor"
        elif (unit_type == "string"):
          self.sensor_type = "text_sensor"
        else:
          self.sensor_type = "sensor"

def read_sensor_metadata(labels_file: str, sensor_limit, sensor_type= None) -> List[SensorMetaData]:
    sensor_meta_data_list: List[SensorMetaData] = []
    sensor_counter: int = 0

    with open(labels_file, encoding='utf-8') as file:
        for line in file:
            if line.strip().startswith('{') and not line.strip().startswith('//'):
                sensor_data = parse_label_def(line)
                if sensor_data is not None and (sensor_type is None or sensor_data.sensor_type == sensor_type):
                  sensor_meta_data_list.append(sensor_data)
                sensor_counter += 1
            if sensor_limit is not None and sensor_counter >= sensor_limit:
                break

    print(f"Total sensors parsed: {sensor_counter}")
    return sensor_meta_data_list

def parse_label_def(line) -> SensorMetaData:
    # Regular expression to match the LabelDef structure
    pattern = r'\{(0x[0-9A-F]+),(\d+),(\d+),(\d+),(-?\d+),"([^"]+)",\s+"([^"]+)",\s+"([^"]+)"\}'
    match = re.match(pattern, line.strip())
    if match:
        _, _, _, _, _, description, unit_type, unique_id = match.groups()
        return SensorMetaData(description, unit_type, unique_id)
    return None

def generate_config_schema_entry(sensor_data: SensorMetaData, constants: Set):
    def remember(const_val: str) -> str:
        constants.add(const_val)
        return const_val

    unit_of_measurement = None
    accuracy_decimals = None
    device_class = None
    state_class= None
    icon = None

    sensor_type = sensor_data.sensor_type
    cv = ""
    if (sensor_type == "sensor"):
      cv  += f"      cv.Optional('{sensor_data.unique_id}'): sensor.sensor_schema(\n"
      state_class= remember("STATE_CLASS_MEASUREMENT")
      accuracy_decimals = 0
    elif (sensor_type == "text_sensor"):
      cv  += f"      cv.Optional('{sensor_data.unique_id}'): text_sensor.text_sensor_schema(\n"
    elif (sensor_type == "binary_sensor"):
      cv  += f"      cv.Optional('{sensor_data.unique_id}'): binary_sensor.binary_sensor_schema(\n"

    unit_type = sensor_data.unit_type
    if (unit_type == "kW"):
      unit_of_measurement = remember("UNIT_KILOWATT")
      accuracy_decimals= 1
      device_class= remember("DEVICE_CLASS_ENERGY")
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type == "A"):
      unit_of_measurement = remember("UNIT_AMPERE")
      accuracy_decimals= 1
      device_class= remember("DEVICE_CLASS_CURRENT")
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type == "V"):
      unit_of_measurement = remember("UNIT_VOLT")
      accuracy_decimals= 1
      device_class= remember("DEVICE_CLASS_VOLTAGE")
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type == "°C"):
      unit_of_measurement = remember("UNIT_CELSIUS")
      accuracy_decimals= 1
      device_class= remember("DEVICE_CLASS_TEMPERATURE")
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type == "U/s"):
      unit_of_measurement = remember("UNIT_REVOLUTIONS_PER_MINUTE")
      accuracy_decimals= 1
      state_class= remember("STATE_CLASS_MEASUREMENT")
      # icon=remember("ICON_FAN"),
    elif (unit_type == "l/min"):
      unit_of_measurement = "UNIT_LITRE_PER_MINUTE"
      accuracy_decimals= 1
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type == "bar"):
      unit_of_measurement = "UNIT_BAR"
      accuracy_decimals= 1
      state_class= remember("STATE_CLASS_MEASUREMENT")
    elif (unit_type not in ["bool", "string", "number"]):
      print("UNEXPECTED UNIT: " + sensor_data.unique_id + ": " + unit_type)

    if unit_of_measurement is not None:
      cv += f"          unit_of_measurement={unit_of_measurement},\n"
    if accuracy_decimals is not None:
      cv += f"          accuracy_decimals={accuracy_decimals},\n"
    if device_class is not None:
      cv += f"          device_class={device_class},\n"
    if state_class is not None:
      cv += f"          state_class={state_class},\n"
    if icon is not None:
      cv += f"          icon={icon},\n"
    cv += "      ),\n"

    return cv

def generate_config_schema(sensor_data_list: List[SensorMetaData], sensor_type: str, filename: str):
    current_filename = os.path.basename(__file__)
    header = (
        f"# Generated by {current_filename}\n"
        "import esphome.codegen as cg\n"
        "import esphome.config_validation as cv\n"
        "from .. import CONF_COMP_ID, ESPAlthermaComponent\n"
        f"from esphome.components import {sensor_type}\n"
        "\n"
    )

    constants: Set[str] = set()

    conf_schema = (
        "CONFIG_SCHEMA = cv.Schema(\n"
        "    {\n"
        "      cv.GenerateID(CONF_COMP_ID): cv.use_id(ESPAlthermaComponent),\n"
    )

    for sensor_data in sensor_data_list:
        if (sensor_data.sensor_type == sensor_type):
          conf_schema += generate_config_schema_entry(sensor_data, constants)

    conf_schema += ( "    }\n"
        ")\n"
    )

    esphome_const = ( "from esphome.const import (\n"
                      "    CONF_ID,\n"
    )
    for c in constants:
       esphome_const += f"    {c},\n"
    esphome_const += ")\n"
    if sensor_type == "sensor":
      esphome_const += ("UNIT_LITRE_PER_MINUTE = 'l/min'\n"
                        "UNIT_BAR = 'bar'\n"
                        "\n"
      )

    target_file = f'gen/{filename}'
    print(f"Writing {target_file}")
    with open(target_file, 'w', encoding='utf-8') as file:
        file.write(header)
        file.write(esphome_const)
        file.write(conf_schema)


def generate_sensor_list_entry(sensor_data: SensorMetaData):
    # Generate YAML configuration
    if (sensor_data.sensor_type == 'binary_sensor'):
      yaml  = f"- platform: espaltherma_exc\n"
      yaml += f"  name: \"{sensor_data.description}\"\n"
      yaml += f"  id: {sensor_data.unique_id}\n"
      yaml += f"  espaltherma_id: espalterma_controller\n"
      yaml += f"  # max_retries: {3}\n"
      yaml += f"  # retry_interval_ms: {1000}\n"
    else:
      yaml  = f"{sensor_data.unique_id}:\n"
      yaml += f"  name: \"{sensor_data.description}\"\n"
      yaml += f"  id: {sensor_data.unique_id}\n"

    # Try out whether this helps to avoid that Heizstab values are no in sync between ESP and home assistant
    if (sensor_data.unique_id == "heizstab_stufe_1" or sensor_data.unique_id == "heizstab_stufe_2"):
      yaml += f"  publish_initial_state: true\n"

    return yaml

def generate_sensor_list(sensor_data_list: List[SensorMetaData], sensor_type: str, filename: str):
    current_filename = os.path.basename(__file__)
    sensors_yaml = (
        f"# Generated by {current_filename}\n"
        "# Include in ESPHome yaml like this\n"
        f"# {sensor_type}:\n"
        f"#   - !include ./common/external_components/espaltherma_exc/gen/{filename}\n"
        "\n"
    )
    if (sensor_type != 'binary_sensor'):
        sensors_yaml += "platform: espaltherma_exc\n"

    for sensor_data in sensor_data_list:
      if (sensor_data.sensor_type == sensor_type):
        sensors_yaml += generate_sensor_list_entry(sensor_data)

    target_file = f'gen/{filename}'
    print(f"Writing {target_file}")
    with open(target_file, 'w', encoding='utf-8') as file:
        file.write(sensors_yaml)

def main():
    labels_file = 'labelDefinitions.h'
    sensor_limit = None
    sensor_data_list = read_sensor_metadata(labels_file, sensor_limit)

    generate_config_schema(sensor_data_list, "sensor", "sensor_config_schema.py")
    generate_config_schema(sensor_data_list, "text_sensor", "text_sensor_config_schema.py")
    generate_config_schema(sensor_data_list, "binary_sensor", "binary_sensor_config_schema.py")

    generate_sensor_list(sensor_data_list, "sensor", "sensor_list.yaml")
    generate_sensor_list(sensor_data_list, "text_sensor", "text_sensor_list.yaml")
    generate_sensor_list(sensor_data_list, "binary_sensor", "binary_sensor_list.yaml")

if __name__ == "__main__":
    main()